-- Update products table with new fields
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS original_price DECIMAL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sale_end_date TIMESTAMPTZ DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_visible BOOLEAN DEFAULT TRUE;
